<?php

namespace AppBundle\Repository;

/**
 * FacteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacteurRepository extends \Doctrine\ORM\EntityRepository
{
}
